version: '3.5'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017

  app:
    container_name: motion-picture
    build:
      context: ./
      target: production
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3003:3000'
    depends_on:
      - mongodb


volumes:
  mongodb_data_container:
